Models/Cust.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Customer.Models
{
    public class Cust
    {
        [DisplayName("Müşteri No")]
        public Guid ID { get; set; }

        [DisplayName("Müşteri Adı")]
        [Required(ErrorMessage = "Zorunludur")]
        public string Name { get; set; }

        [DisplayName("Müşteri Borcu")]
        [DisplayFormat(DataFormatString = "{0:c}")]  
        //[RegularExpression(@"(^(?!0*\.0+$)\d*(?:\.\d+)?$)", ErrorMessage = "Geçerli yazım formatı 12.75 ")]
        public decimal Debt { get; set; }

        [DisplayName("Aktif / Pasif")]        
        public bool Disabled { get; set; }

        [DisplayName("Müşteri Açılış")]
        public DateTimeOffset? OpeningDate { get; set; }
    }
}

Models/CustViewModel.cs
using System.Collections.Generic;

namespace Customer.Models
{
    public class CustViewModel
    {       
         public IEnumerable<Cust> Custs { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Customer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CustController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Customer.Services;
using Customer.Models;

namespace Customer.Controllers
{
 
 // CustController => ICustService : Bağlı (Dependency injection) hale getirdik.
   public class CustController : Controller
   {
       
               // ICustService referenasını(pointer) tutar
        private readonly ICustService _custService;

        public CustController(ICustService custService)
        {
            _custService = custService;
        }

                //public IActionResult Index()
        public async Task<IActionResult> Index()
        {
            var custs = await _custService.GetCustItemsAsync();


            var model = new CustViewModel()
            {
                Custs = custs
            };

            return View(model);
        }

       
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCust(Cust newCust)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var successful = await _custService.AddCustAsync(newCust);
            if (!successful) 
            {
                return BadRequest("Müşteri eklenemedi.");
            }

            return RedirectToAction("Index");
        }


        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DelCust(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }

            var successful = await _custService.DelCustAsync(id);
            if (!successful)
            {
                return BadRequest("Silme işlemi yapılamadı.");
            }

            return RedirectToAction("Index");
        }


   }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Customer.Models;

namespace Customer.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cust/AddCustPartial.cshtml
@model Cust

<!-- Asp-action etiketi yardımcısı form için bir URL oluşturabilir -->

<form asp-action="AddCust" method="POST">
    <!-- asp-for oluşturduğun model e göre bağlantı -->
    <label asp-for="Name">Müşteri Adı:</label>
    <input asp-for="Name">

    <label asp-for="Debt">Müşteri Borcu:</label>
    <input asp-for="Debt">
    <button type="submit">Ekle</button>
</form>

Views/Cust/Index.cshtml
@model CustViewModel;

@{
    ViewData["Title"] = "Müşteriler";
}

<div class="panel panel-default cust-panel">
  <div class="panel-heading">@ViewData["Title"]</div>

  <table class="table table-hover">
      <thead>
          <tr>   
              <td>Müşteri Adı</td>   
              <td>Müşteri Borcu</td>      
              <td>Müşteri Durumu</td>      
              <td>İşlem</td>     
          </tr>
      </thead>

      @foreach (var item in Model.Custs)
      {
          <tr>                    
              <td class="name">@item.Name</td>
              <td>@item.Debt</td>
              <td> @(item.Disabled ? "Pasif" : "Aktif" ) </td>
              <td>
                    <form asp-action="DelCust" method="POST">
                    <button type="submit" class="dell-button" >Sil</button>
                    <input type="hidden" name="ID" value="@item.ID">                    
                </form>
                <button type="submit" value="@item.ID" class="select-button">Seç</button>                  
               </td>
          </tr>
      }
  </table>


  <div class="panel-footer add-item-form">
      @await Html.PartialAsync("AddCustPartial", new Cust())
  </div>

  
  <div class="panel-footer upd-item-form" style="display:none" >
      @await Html.PartialAsync("UpdCustPartial", new Cust())
  </div>

Views/Cust/UpdCustPartial.cshtml
@model Cust

<!-- Asp-action etiketi yardımcısı form için bir URL oluşturabilir -->

<form asp-action="UpdCust" method="POST">
    <!-- asp-for oluşturduğun model e göre bağlantı -->
    <input asp-for="ID" type="hidden" >

    <label asp-for="Name" >Müşteri Adı:</label>
    <input asp-for="Name">

    <label asp-for="Debt">Müşteri Borcu:</label>
    <input asp-for="Debt">

    <label asp-for="Disabled">Müşteri Borcu:</label>
    <input asp-for="Disabled" type="checkbox"> Aktif / Pasif <br>

    <button type="submit" id="btnUpd">Güncelle</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
        <h1>Notlar</h1>

<p>* Dependency injection (Bağımlılık Enjeksiyonu)</p>
<p>* ASP.NET multitreading ve asenkron işler(tasks) için çok uygundur.</p>
<p>* CsharpHelloWorld.csproj => npm (project.json) gibidir.</p>
<p>* Task<IEnumerable<Cust>> : Müşteriler için yapılacaklar içeren görev listesi <br>
  asenkron: db den gelen listenin ne zaman döneceğini bilmediğimizden, bu yapı seçilir. </p>
<p>* Servis Sınıfları kullanır:<br>
&nbsp; Kontrol daha sade olur, <br>
&nbsp; test etmek kolaydır,<br>
&nbsp; db değişiklik yapma kolaydır. <br><br>

    
&nbsp;    Uygulama: Mantık, DB, Uygulama katmanı olarak ayrılır, bunu 3-ties / n-tier mimari denir.<br>
&nbsp;    Interface: (methodların ve özelliklerin) işi yapan sınıftan ayrılmasmı<br>
&nbsp;&nbsp;        test etmeyi kolaylaştırır. </p>

 <p>* Kontrolün yapısı methoduna servisi tanımladığımızda bağımlılık Enjeksiyonu yapmış oluruz. <br>
&nbsp;    kontrolünü ilk satırına servis referansını(pointer) tutan değişkeni tanımlarız.<br>
&nbsp;    sınıf ilk çalıştığında servisi kontrole enjekte etmiş oluruz. </p>

<p>* Task methodlarında cevap gelene kadar beklememize yarayan await kelimesini kullanılır. </p>

<p>* CustControler > ICustService bağlı hale geldi,<br>
&nbsp;    fakat ICustService arayüzü CustService kullanmısı gerektiğini bilmiyor.3-ties<br>
&nbsp;    Startup.cs sınıfında ki ConfigureServices methoduna bunu söylemek gerekmektedir.<br><br>

&nbsp;    services.AddScoped<ICustService, CustService>();<br><br>

&nbsp;&nbsp;        CustControler > ICustService > CustService<br><br>

&nbsp;  CustControler > ICustService > <br>
&nbsp;&nbsp;    Startup > ConfigureServices ><br>
        AddScoped > CustService<br>
</p>

<p>ORM Ibject Relational Mapper <br>
EF: <br>
Db baglanma kolaylığı, <br>
sorguları oluşturma ve tekrar obje haline getirme.3-ties.3-ties.<br>
Farklı db lere bağlanma kolaylığı sağlar. 
</p>

<p>Db ile nasıl iletişime geçileceğini, okuma ve yazma işlemi veri tabanı kaynığı(context) sınıfı ile sağlanır.<br>
Bağlantı yolu, appsettings.json içerisinde DataSource alanına yazılır.
</p>

<p> Migration(Göç) Oluşturma:<br><br>

            1. [ dotnet ef migrations add tCust ]<br>
            * Program.cs klasöründe olduğunuzdan emin olunuz.<br><br>

            2. [ dotnet ef migrations list ] : Göç listesini <br><br>

            3. [ dotnet ef database update ]<br><br>

            4. [ dotnet ef database update CreateIdentitySchema ] <br>
            Bu komut CreateIdentitySchema dan sonra oluşturulmuş <br>
            tüm *göçlerin Down metodunu çalıştıracaktır.<br><br>

            5. veri tabanını tamamen silmek istiyorsanız. <br>
                [ dotnet ef database drop ] kullanabilirsiniz. <br>
                Ardından [ dotnet ef database update ]<br>
                yazdığınızda son Göç e kadar tüm göçler çalıştırılır.
</p>

<p>
    docker pull microsoft/dotnet <br>

    Dockerfile <br>

FROM microsoft/dotnet:2.2-sdk AS build<br>
COPY Customer/*.csproj ./app/Customer/<br>
WORKDIR /app/Customer<br>
RUN dotnet restore<br><br>

COPY Customer/. ./Customer/<br>
RUN dotnet publish -o out /p:PublishWithAspNetCoreTargetManifest="false"<br><br>

FROM microsoft/dotnet:2.2-runtime AS runtime<br>
ENV ASPNETCORE_URLS http://+:80<br>
WORKDIR /app<br>
COPY --from=build /app/Customer/out ./<br>
ENTRYPOINT ["dotnet", "Customer.dll"]<br><br>

    Image yaratmak: <br>
    
    docker build -t Customer .
    docker run --name Customer_sample --rm -it -p 8080:80 Customer<br><br>

    nginx/Dockerfile<br>
    
    



</p>
</div>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Müşteriler</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Customer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cust" asp-action="Index">Müşteriler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Customer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>